In [1]:
x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

#evaluation our model using this test dataset
x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]]

In [3]:
import tensorflow as tf

In [8]:
X = tf.placeholder('float', [None,3])
Y = tf.placeholder('float', [None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

#correct prediction test model
prediction = tf.arg_max(hypothesis,1)
is_correct = tf.equal(prediction, tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

#launch graph
with tf.Session() as sess:
    #initialize tensorflow variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict={X: x_data, Y:y_data})
        print(step, cost_val, W_val,'\n')
    
    #predict
    print('Prediction:', sess.run(prediction, feed_dict={X: x_test}))
    #caculate the accuracy
    print('Accuracy:', sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))

0 7.7444763 [[-0.10079545 -0.4203277  -0.6742114 ]
 [-0.40040308  0.58891726 -0.654435  ]
 [-0.06634343 -2.1062694   0.97937703]] 

1 4.4631276 [[-0.09052564 -0.38931626 -0.7154926 ]
 [-0.28490943  0.74901587 -0.93002725]
 [ 0.05968171 -1.9271551   0.6742377 ]] 

2 2.9361134 [[-0.13479057 -0.3623453  -0.6981986 ]
 [-0.45658827  0.89523524 -0.9045677 ]
 [-0.09976079 -1.7574329   0.663958  ]] 

3 2.2808743 [[-0.13686275 -0.35362372 -0.704848  ]
 [-0.41478264  0.95122546 -1.0023636 ]
 [-0.05779784 -1.6545963   0.5191584 ]] 

4 2.0531294 [[-0.15579604 -0.35331774 -0.6862207 ]
 [-0.45639876  0.96137714 -0.9708991 ]
 [-0.11241053 -1.593421    0.51259583]] 

5 2.0001464 [[-0.16084021 -0.36169934 -0.67279494]
 [-0.42732593  0.92396617 -0.96256095]
 [-0.09437963 -1.5768898   0.47803366]] 

6 1.9647747 [[-0.17218512 -0.36656496 -0.65658444]
 [-0.4297116   0.9054684  -0.9416775 ]
 [-0.10918987 -1.5428586   0.4588128 ]] 

7 1.9334619 [[-0.18079978 -0.37308377 -0.64145094]
 [-0.41805747  0.87768936

170 0.64870054 [[-1.35138    -0.7683188   0.92436445]
 [-0.02608963 -0.2271038  -0.21272722]
 [-0.08632079 -0.18481916 -0.92209524]] 

171 0.6476105 [[-1.356051   -0.7690101   0.92972684]
 [-0.02581649 -0.2268059  -0.21329828]
 [-0.084727   -0.18463092 -0.9238773 ]] 

172 0.6465292 [[-1.3607081  -0.7696902   0.9350641 ]
 [-0.0255461  -0.226505   -0.21386957]
 [-0.08313648 -0.18445061 -0.92564815]] 

173 0.6454567 [[-1.3653516  -0.77035916  0.94037646]
 [-0.02527833 -0.2262014  -0.21444094]
 [-0.08154912 -0.18427812 -0.92740804]] 

174 0.64439285 [[-1.3699814  -0.77101713  0.9456642 ]
 [-0.02501321 -0.22589521 -0.21501225]
 [-0.07996498 -0.18411312 -0.9291572 ]] 

175 0.6433376 [[-1.3745978  -0.7716642   0.9509277 ]
 [-0.02475067 -0.22558662 -0.21558337]
 [-0.07838401 -0.1839554  -0.93089586]] 

176 0.6422906 [[-1.3792008  -0.7723005   0.956167  ]
 [-0.02449065 -0.22527583 -0.21615417]
 [-0.07680617 -0.18380478 -0.93262434]] 

177 0.6412519 [[-1.3837907  -0.77292603  0.96138245]
 [-0.02

## Learning rate : NaN

1. large learning rate : overshooting
2. small learning rate : many iterations until convergence and trapping in local minima

In [11]:
#learning_rate 를 1.5로 한 경우

X = tf.placeholder('float', [None,3])
Y = tf.placeholder('float', [None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1.5).minimize(cost)

#correct prediction test model
prediction = tf.arg_max(hypothesis,1)
is_correct = tf.equal(prediction, tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

#launch graph
with tf.Session() as sess:
    #initialize tensorflow variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        if step%20 ==0:
            cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict={X: x_data, Y:y_data})
            print(step, cost_val, W_val,'\n')
     
    #predict
    print('Prediction:', sess.run(prediction, feed_dict={X: x_test}))
    #caculate the accuracy
    print('Accuracy:', sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))

0 4.605617 [[ 1.210855    0.17893243  0.7891227 ]
 [ 3.1748695  -3.2512991   1.2147204 ]
 [ 1.5715561  -3.6485271   1.2037753 ]] 

20 23.220043 [[ 0.08882427  0.7414324   1.3486533 ]
 [-0.94387245 -0.62629914  2.7084627 ]
 [-2.5479536  -0.83602715  2.5107849 ]] 

40 26.841227 [[ 0.4638242   1.3039172   0.41116858]
 [ 1.4936275   1.9986703  -2.3540068 ]
 [-0.11045361  1.9764576  -2.7391999 ]] 

60 15.082949 [[ 0.8386834   0.36655796  0.9736686 ]
 [ 3.9308362  -1.9385383  -0.85400677]
 [ 2.3268952  -1.7733915  -1.4266999 ]] 

80 25.09394 [[-0.28631562  0.92905784  1.5361677 ]
 [-0.19416189  0.6864612   0.64599156]
 [-1.7981038   1.0391085  -0.11420071]] 

100 8.571569 [[ 0.08867216  0.02789086  2.062347  ]
 [ 2.2433133  -3.1663625   2.0613403 ]
 [ 0.6393838  -2.659435    1.1468552 ]] 

120 18.819302 [[ 0.45899484  0.59039086  1.1295242 ]
 [ 4.6642404  -0.5413625  -2.9845867 ]
 [ 3.0630286   0.15306497 -4.0892897 ]] 

140 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]] 

160 nan [[nan n

## Non-normalized inputs : NaN

In [13]:
import numpy as np

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.23, 1098100, 809.780029, 813.669983],
              [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [16]:
x_data = xy[:,0:-1]
y_data = xy[:, [-1]]

X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([4,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(201) :
    if step%10 == 0:
        cost_val, hy_val, _ = sess.run(
            [cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
        print(step, 'Cost: ', cost_val, '\nPrediction:\n', hy_val)

0 Cost:  7604855600000.0 
Prediction:
 [[-1944427.9]
 [-3915171.8]
 [-3079753.2]
 [-2158651. ]
 [-2544227. ]
 [-2565647.8]
 [-2351444.8]
 [-2994077.8]]
10 Cost:  8.355308e+27 
Prediction:
 [[6.4478146e+13]
 [1.2980112e+14]
 [1.0210986e+14]
 [7.1578465e+13]
 [8.4359046e+13]
 [8.5069083e+13]
 [7.7968756e+13]
 [9.9269730e+13]]
20 Cost:  inf 
Prediction:
 [[-2.1372154e+21]
 [-4.3024337e+21]
 [-3.3845694e+21]
 [-2.3725652e+21]
 [-2.7961949e+21]
 [-2.8197299e+21]
 [-2.5843797e+21]
 [-3.2904292e+21]]
30 Cost:  inf 
Prediction:
 [[7.0840885e+28]
 [1.4260997e+29]
 [1.1218612e+29]
 [7.8641871e+28]
 [9.2683649e+28]
 [9.3463746e+28]
 [8.5662755e+28]
 [1.0906572e+29]]
40 Cost:  inf 
Prediction:
 [[-2.3481166e+36]
 [-4.7269994e+36]
 [-3.7185599e+36]
 [-2.6066908e+36]
 [-3.0721243e+36]
 [-3.0979818e+36]
 [-2.8394074e+36]
 [-3.6151303e+36]]
50 Cost:  inf 
Prediction:
 [[inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]]
60 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 

### ★ normalized inputs => min-max scale

In [28]:
from sklearn.preprocessing import MinMaxScaler

xy = MinMaxScaler(xy)
print(xy)

MinMaxScaler(copy=True,
             feature_range=MinMaxScaler(copy=True,
                                        feature_range=MinMaxScaler(copy=True,
                                                                   feature_range=MinMaxScaler(copy=True,
                                                                                              feature_range=array([[8.28659973e+02, 8.33450012e+02, 9.08100000e+05, 8.28349976e+02,
        8.31659973e+02],
       [8.23020020e+02, 8.28070007e+02, 1.82810000e+06, 8.21655029e+02,
        8.28070007e+02],
       [8.19929993e+02, 8.24400024e+02, 1.43810000...
       [8.16000000e+02, 8.20958984e+02, 1.00810000e+06, 8.15489990e+02,
        8.19239990e+02],
       [8.19359985e+02, 8.23000000e+02, 1.18810000e+06, 8.18469971e+02,
        8.18979980e+02],
       [8.19000000e+02, 8.23000000e+02, 1.19810000e+06, 8.16000000e+02,
        8.20450012e+02],
       [8.11700012e+02, 8.15230000e+02, 1.09810000e+06, 8.09780029e+02,
        8.13669983e+02]