In [1]:
import tensorflow

In [2]:
import matplotlib

## tensorflow 실습

### ※ components in tensorflow

1 . constant : a non-mutable variable

2 . placeholder : a tensor taking external inputs(input data)

3 . variable : a mutable variable(parameter)

In [2]:
import tensorflow as tf

In [2]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) #also tf.float32 implicitly
total = a+b
print(a)
print(b)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


In [3]:
a = tf.constant([3.0,4.0], dtype=tf.float32)
print(a)

Tensor("Const_2:0", shape=(2,), dtype=float32)


In [4]:
#결과값 3+4 를 얻기위해서 : session 사용 3단계

a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) #also tf.float32 implicitly
total = a+b

sess=tf.Session()
print(sess.run(total))
print(sess.run([a,b]))
sess.close()

7.0
[3.0, 4.0]


In [5]:
a = tf.constant([3.0,4.0], dtype=tf.float32)
sess = tf.Session()
print(sess.run(a))
sess.close()

[3. 4.]


In [6]:
#building computational graph : placeholder

x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x+y
print(x)
print(y)
print(z)

Tensor("Placeholder:0", dtype=float32)
Tensor("Placeholder_1:0", dtype=float32)
Tensor("add_2:0", dtype=float32)


In [7]:
x1 = tf.placeholder(tf.float32)
y1 = tf.placeholder(tf.float32)
z1 = x1+y1
print(x1)
print(y1)
print(z1)

Tensor("Placeholder:0", dtype=float32)
Tensor("Placeholder_1:0", dtype=float32)
Tensor("add_2:0", dtype=float32)


In [4]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x+y
sess = tf.Session()
print(sess.run(z, feed_dict={x:3, y:4.5}))
sess.close()

7.5


In [10]:
x1 = tf.placeholder(tf.float32)
y1 = tf.placeholder(tf.float32)
z1 = x1+y1
sess = tf.Session()
print(sess.run(z1, feed_dict={x1:[1,3],y1:[2,4]}))
sess.close()

[3. 7.]


In [11]:
#building computational graph : variable

my_variable = tf.Variable('my_variable',[1,2,3])
print(my_variable)

<tf.Variable 'Variable:0' shape=() dtype=string_ref>


In [17]:
my_variable1 = tf.get_variable('my_variable1',[1,2,3])
my_int_variable = tf.get_variable('my_int_variable',[1,2,3], dtype=tf.int32, initializer=tf.zeros_initializer)
print(my_variable)
print(my_int_variable)

<tf.Variable 'my_variable:0' shape=(1, 2, 3) dtype=float32_ref>
<tf.Variable 'my_int_variable:0' shape=(1, 2, 3) dtype=int32_ref>


In [19]:
v = tf.get_variable('v',[1,2,3],dtype=tf.float32)
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(v))

[[[ 0.8659383   0.9985938   0.48453903]
  [-0.25308514 -0.34336346 -1.0033226 ]]]


In [1]:
import tensorflow as tf
sess = tf.Session()

In [2]:
v1 = tf.get_variable('v1',[1,2,3],dtype=tf.int32, initializer=tf.zeros_initializer)
v2 = tf.get_variable('v2',[1,2,3],dtype=tf.float32, initializer=tf.constant_initializer(1.0))
sess=tf.Session()
sess.run(tf.global_variables_initializer())
o1,o2 = sess.run([v1,v2])
print(o1)
print(o2)

[[[0 0 0]
  [0 0 0]]]
[[[1. 1. 1.]
  [1. 1. 1.]]]


In [3]:
my_variable = tf.Variable('my_variable',[1,2,3])
print(my_variable)

<tf.Variable 'Variable:0' shape=() dtype=string_ref>


In [4]:
#같은 변수를 또 사용하면 에러 -> 문제 해결 : variable_scope

with tf.variable_scope('foo'):
    my_variable = tf.get_variable('my_variable',[1])
with tf.variable_scope('foo', reuse=True):
    dup = tf.get_variable('my_variable',[1])

print(my_variable)
print(dup)

W0819 16:23:01.007995 140030538225408 deprecation.py:506] From /home/pirl/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


<tf.Variable 'foo/my_variable:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'foo/my_variable:0' shape=(1,) dtype=float32_ref>


In [5]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(my_variable))
    print(sess.run(dup))

[-0.7855999]
[-0.7855999]


In [6]:
#examples

x=tf.placeholder(tf.float32)
w=tf.get_variable('w',initializer=tf.constant([2.]))
b=tf.constant(4.0)
y=x*w+b

print(x)
print(w)

Tensor("Placeholder:0", dtype=float32)
<tf.Variable 'w:0' shape=(1,) dtype=float32_ref>


In [7]:
print(b)
print(y)

Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", dtype=float32)


In [8]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(y,feed_dict={x:1}))

[6.]


In [10]:
x1 = tf.placeholder(tf.float32, shape=[1])
w1 = tf.get_variable('w1',shape=[1],initializer=tf.zeros_initializer)
b1 = tf.constant([4.0])
y1 = x1*w1 + b1

print(x1)
print(w1)
print(b1)
print(y1)

Tensor("Placeholder_2:0", shape=(1,), dtype=float32)
<tf.Variable 'w1:0' shape=(1,) dtype=float32_ref>
Tensor("Const_2:0", shape=(1,), dtype=float32)
Tensor("add_1:0", shape=(1,), dtype=float32)


In [13]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(y1, feed_dict={x1:[1]}))

[4.]


In [15]:
x2 = tf.placeholder(tf.float32, shape=[None,2])
w2 = tf.get_variable('w2',shape=[2], initializer=tf.random_normal_initializer())
y2= x2*w2

print(x2)
print(w2)
print(y2)

Tensor("Placeholder_3:0", shape=(?, 2), dtype=float32)
<tf.Variable 'w2:0' shape=(2,) dtype=float32_ref>
Tensor("mul_2:0", shape=(?, 2), dtype=float32)


In [17]:
import numpy as np
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(y2,feed_dict={x2:np.random.rand(3,2)}))

[[ 0.14674066 -0.07354963]
 [ 0.17337331 -0.23961869]
 [ 0.00165184 -0.16753231]]
